# Copyright (c) 2021-2026, PostgreSQL Global Development Group

"""Port of src/test/subscription/t/008_diff_schema.pl.

Test behaviour when the subscriber table has extra columns: replicated rows get
local defaults for them and locally-changed values are retained, a replica
identity column added before it exists on the publisher works, and a missing
replicated column reports the expected error.
"""


def test_diff_schema(create_pg):
    publisher = create_pg("publisher", allows_streaming="logical")
    subscriber = create_pg("subscriber")

    publisher.sql("CREATE TABLE test_tab (a int primary key, b varchar)")
    publisher.sql("INSERT INTO test_tab VALUES (1, 'foo'), (2, 'bar')")
    subscriber.sql(
        "CREATE TABLE test_tab (a int primary key, b text, c timestamptz DEFAULT now(), "
        "d bigint DEFAULT 999, e int GENERATED BY DEFAULT AS IDENTITY)"
    )

    publisher.sql("CREATE PUBLICATION tap_pub FOR ALL TABLES")
    subscriber.sql(
        f"CREATE SUBSCRIPTION tap_sub CONNECTION '{publisher.connstr()}' PUBLICATION tap_pub"
    )
    subscriber.wait_for_subscription_sync(publisher, "tap_sub")

    assert subscriber.sql(
        "SELECT count(*), count(c), count(d = 999) FROM test_tab"
    ) == (2, 2, 2), "check initial data was copied to subscriber"

    # Updating on the publisher must not change the subscriber's extra columns.
    publisher.sql("UPDATE test_tab SET b = encode(sha256(b::bytea), 'hex')")
    publisher.wait_for_catchup("tap_sub")
    assert subscriber.sql(
        "SELECT count(*), count(c), count(d = 999), count(e) FROM test_tab"
    ) == (2, 2, 2, 2), "check extra columns contain local defaults after copy"

    # Locally changed extra-column values are retained across apply.
    subscriber.sql(
        "UPDATE test_tab SET c = 'epoch'::timestamptz + 987654321 * interval '1s'"
    )
    publisher.sql("UPDATE test_tab SET b = encode(sha256(a::text::bytea), 'hex')")
    publisher.wait_for_catchup("tap_sub")
    assert subscriber.sql(
        "SELECT count(*), count(extract(epoch from c) = 987654321), count(d = 999) FROM test_tab"
    ) == (2, 2, 2), "check extra columns contain locally changed data"

    publisher.sql("INSERT INTO test_tab VALUES (3, 'baz')")
    publisher.wait_for_catchup("tap_sub")
    assert subscriber.sql(
        "SELECT count(*), count(c), count(d = 999), count(e) FROM test_tab"
    ) == (3, 3, 3, 3), "check extra columns contain local defaults after apply"

    # A replica identity column added on the subscriber before it is mapped to
    # a publisher column must not stall replication.
    publisher.sql("CREATE TABLE test_tab2 (a int)")
    subscriber.sql("CREATE TABLE test_tab2 (a int)")
    subscriber.sql("ALTER SUBSCRIPTION tap_sub REFRESH PUBLICATION")
    subscriber.wait_for_subscription_sync()
    subscriber.sql("ALTER TABLE test_tab2 ADD COLUMN b serial PRIMARY KEY")
    publisher.sql("INSERT INTO test_tab2 VALUES (1)")
    publisher.wait_for_catchup("tap_sub")
    assert subscriber.sql("SELECT count(*), min(a), max(a) FROM test_tab2") == (
        1,
        1,
        1,
    ), "check replicated inserts on subscriber"

    # A subscriber table missing replicated columns reports the expected error.
    publisher.sql("CREATE TABLE test_tab3 (a int, b int, c int)")
    subscriber.sql("CREATE TABLE test_tab3 (a int)")
    offset = subscriber.current_log_position()
    subscriber.sql("ALTER SUBSCRIPTION tap_sub REFRESH PUBLICATION")
    subscriber.wait_for_log(
        r"ERROR: ( [A-Z0-9]+:)? logical replication target relation "
        r'"public.test_tab3" is missing replicated columns: "b", "c"',
        offset,
    )
