# Copyright (c) 2025, PostgreSQL Global Development Group
# This file is generated by src/tools/generate_pytest_libpq_errors.py - do not edit directly.

"""
Generated PostgreSQL error classes mapped from SQLSTATE codes.
"""

from typing import Dict

from ._error_base import LibpqError, LibpqWarning


class SuccessfulCompletion(LibpqError):
    """SQLSTATE 00000 - successful completion."""

    pass


class Warning(LibpqWarning):
    """SQLSTATE 01000 - warning."""

    pass


class DynamicResultSetsReturnedWarning(Warning):
    """SQLSTATE 0100C - dynamic result sets returned."""

    pass


class ImplicitZeroBitPaddingWarning(Warning):
    """SQLSTATE 01008 - implicit zero bit padding."""

    pass


class NullValueEliminatedInSetFunctionWarning(Warning):
    """SQLSTATE 01003 - null value eliminated in set function."""

    pass


class PrivilegeNotGrantedWarning(Warning):
    """SQLSTATE 01007 - privilege not granted."""

    pass


class PrivilegeNotRevokedWarning(Warning):
    """SQLSTATE 01006 - privilege not revoked."""

    pass


class StringDataRightTruncationWarning(Warning):
    """SQLSTATE 01004 - string data right truncation."""

    pass


class DeprecatedFeatureWarning(Warning):
    """SQLSTATE 01P01 - deprecated feature."""

    pass


class NoData(LibpqError):
    """SQLSTATE 02000 - no data."""

    pass


class NoAdditionalDynamicResultSetsReturned(NoData):
    """SQLSTATE 02001 - no additional dynamic result sets returned."""

    pass


class SQLStatementNotYetComplete(LibpqError):
    """SQLSTATE 03000 - sql statement not yet complete."""

    pass


class ConnectionException(LibpqError):
    """SQLSTATE 08000 - connection exception."""

    pass


class ConnectionDoesNotExist(ConnectionException):
    """SQLSTATE 08003 - connection does not exist."""

    pass


class ConnectionFailure(ConnectionException):
    """SQLSTATE 08006 - connection failure."""

    pass


class SQLClientUnableToEstablishSQLConnection(ConnectionException):
    """SQLSTATE 08001 - sqlclient unable to establish sqlconnection."""

    pass


class SQLServerRejectedEstablishmentOfSQLConnection(ConnectionException):
    """SQLSTATE 08004 - sqlserver rejected establishment of sqlconnection."""

    pass


class TransactionResolutionUnknown(ConnectionException):
    """SQLSTATE 08007 - transaction resolution unknown."""

    pass


class ProtocolViolation(ConnectionException):
    """SQLSTATE 08P01 - protocol violation."""

    pass


class TriggeredActionException(LibpqError):
    """SQLSTATE 09000 - triggered action exception."""

    pass


class FeatureNotSupported(LibpqError):
    """SQLSTATE 0A000 - feature not supported."""

    pass


class InvalidTransactionInitiation(LibpqError):
    """SQLSTATE 0B000 - invalid transaction initiation."""

    pass


class LocatorException(LibpqError):
    """SQLSTATE 0F000 - locator exception."""

    pass


class InvalidLocatorSpecification(LocatorException):
    """SQLSTATE 0F001 - invalid locator specification."""

    pass


class InvalidGrantor(LibpqError):
    """SQLSTATE 0L000 - invalid grantor."""

    pass


class InvalidGrantOperation(InvalidGrantor):
    """SQLSTATE 0LP01 - invalid grant operation."""

    pass


class InvalidRoleSpecification(LibpqError):
    """SQLSTATE 0P000 - invalid role specification."""

    pass


class DiagnosticsException(LibpqError):
    """SQLSTATE 0Z000 - diagnostics exception."""

    pass


class StackedDiagnosticsAccessedWithoutActiveHandler(DiagnosticsException):
    """SQLSTATE 0Z002 - stacked diagnostics accessed without active handler."""

    pass


class InvalidArgumentForXquery(LibpqError):
    """SQLSTATE 10608 - invalid argument for xquery."""

    pass


class CaseNotFound(LibpqError):
    """SQLSTATE 20000 - case not found."""

    pass


class CardinalityViolation(LibpqError):
    """SQLSTATE 21000 - cardinality violation."""

    pass


class DataException(LibpqError):
    """SQLSTATE 22000 - data exception."""

    pass


class ArraySubscriptError(DataException):
    """SQLSTATE 2202E - array subscript error."""

    pass


class CharacterNotInRepertoire(DataException):
    """SQLSTATE 22021 - character not in repertoire."""

    pass


class DatetimeFieldOverflow(DataException):
    """SQLSTATE 22008 - datetime field overflow."""

    pass


class DivisionByZero(DataException):
    """SQLSTATE 22012 - division by zero."""

    pass


class ErrorInAssignment(DataException):
    """SQLSTATE 22005 - error in assignment."""

    pass


class EscapeCharacterConflict(DataException):
    """SQLSTATE 2200B - escape character conflict."""

    pass


class IndicatorOverflow(DataException):
    """SQLSTATE 22022 - indicator overflow."""

    pass


class IntervalFieldOverflow(DataException):
    """SQLSTATE 22015 - interval field overflow."""

    pass


class InvalidArgumentForLogarithm(DataException):
    """SQLSTATE 2201E - invalid argument for logarithm."""

    pass


class InvalidArgumentForNtileFunction(DataException):
    """SQLSTATE 22014 - invalid argument for ntile function."""

    pass


class InvalidArgumentForNthValueFunction(DataException):
    """SQLSTATE 22016 - invalid argument for nth value function."""

    pass


class InvalidArgumentForPowerFunction(DataException):
    """SQLSTATE 2201F - invalid argument for power function."""

    pass


class InvalidArgumentForWidthBucketFunction(DataException):
    """SQLSTATE 2201G - invalid argument for width bucket function."""

    pass


class InvalidCharacterValueForCast(DataException):
    """SQLSTATE 22018 - invalid character value for cast."""

    pass


class InvalidDatetimeFormat(DataException):
    """SQLSTATE 22007 - invalid datetime format."""

    pass


class InvalidEscapeCharacter(DataException):
    """SQLSTATE 22019 - invalid escape character."""

    pass


class InvalidEscapeOctet(DataException):
    """SQLSTATE 2200D - invalid escape octet."""

    pass


class InvalidEscapeSequence(DataException):
    """SQLSTATE 22025 - invalid escape sequence."""

    pass


class NonstandardUseOfEscapeCharacter(DataException):
    """SQLSTATE 22P06 - nonstandard use of escape character."""

    pass


class InvalidIndicatorParameterValue(DataException):
    """SQLSTATE 22010 - invalid indicator parameter value."""

    pass


class InvalidParameterValue(DataException):
    """SQLSTATE 22023 - invalid parameter value."""

    pass


class InvalidPrecedingOrFollowingSize(DataException):
    """SQLSTATE 22013 - invalid preceding or following size."""

    pass


class InvalidRegularExpression(DataException):
    """SQLSTATE 2201B - invalid regular expression."""

    pass


class InvalidRowCountInLimitClause(DataException):
    """SQLSTATE 2201W - invalid row count in limit clause."""

    pass


class InvalidRowCountInResultOffsetClause(DataException):
    """SQLSTATE 2201X - invalid row count in result offset clause."""

    pass


class InvalidTablesampleArgument(DataException):
    """SQLSTATE 2202H - invalid tablesample argument."""

    pass


class InvalidTablesampleRepeat(DataException):
    """SQLSTATE 2202G - invalid tablesample repeat."""

    pass


class InvalidTimeZoneDisplacementValue(DataException):
    """SQLSTATE 22009 - invalid time zone displacement value."""

    pass


class InvalidUseOfEscapeCharacter(DataException):
    """SQLSTATE 2200C - invalid use of escape character."""

    pass


class MostSpecificTypeMismatch(DataException):
    """SQLSTATE 2200G - most specific type mismatch."""

    pass


class NullValueNotAllowed(DataException):
    """SQLSTATE 22004 - null value not allowed."""

    pass


class NullValueNoIndicatorParameter(DataException):
    """SQLSTATE 22002 - null value no indicator parameter."""

    pass


class NumericValueOutOfRange(DataException):
    """SQLSTATE 22003 - numeric value out of range."""

    pass


class SequenceGeneratorLimitExceeded(DataException):
    """SQLSTATE 2200H - sequence generator limit exceeded."""

    pass


class StringDataLengthMismatch(DataException):
    """SQLSTATE 22026 - string data length mismatch."""

    pass


class StringDataRightTruncation(DataException):
    """SQLSTATE 22001 - string data right truncation."""

    pass


class SubstringError(DataException):
    """SQLSTATE 22011 - substring error."""

    pass


class TrimError(DataException):
    """SQLSTATE 22027 - trim error."""

    pass


class UnterminatedCString(DataException):
    """SQLSTATE 22024 - unterminated c string."""

    pass


class ZeroLengthCharacterString(DataException):
    """SQLSTATE 2200F - zero length character string."""

    pass


class FloatingPointException(DataException):
    """SQLSTATE 22P01 - floating point exception."""

    pass


class InvalidTextRepresentation(DataException):
    """SQLSTATE 22P02 - invalid text representation."""

    pass


class InvalidBinaryRepresentation(DataException):
    """SQLSTATE 22P03 - invalid binary representation."""

    pass


class BadCopyFileFormat(DataException):
    """SQLSTATE 22P04 - bad copy file format."""

    pass


class UntranslatableCharacter(DataException):
    """SQLSTATE 22P05 - untranslatable character."""

    pass


class NotAnXmlDocument(DataException):
    """SQLSTATE 2200L - not an xml document."""

    pass


class InvalidXmlDocument(DataException):
    """SQLSTATE 2200M - invalid xml document."""

    pass


class InvalidXmlContent(DataException):
    """SQLSTATE 2200N - invalid xml content."""

    pass


class InvalidXmlComment(DataException):
    """SQLSTATE 2200S - invalid xml comment."""

    pass


class InvalidXmlProcessingInstruction(DataException):
    """SQLSTATE 2200T - invalid xml processing instruction."""

    pass


class DuplicateJsonObjectKeyValue(DataException):
    """SQLSTATE 22030 - duplicate json object key value."""

    pass


class InvalidArgumentForSQLJsonDatetimeFunction(DataException):
    """SQLSTATE 22031 - invalid argument for sql json datetime function."""

    pass


class InvalidJsonText(DataException):
    """SQLSTATE 22032 - invalid json text."""

    pass


class InvalidSQLJsonSubscript(DataException):
    """SQLSTATE 22033 - invalid sql json subscript."""

    pass


class MoreThanOneSQLJsonItem(DataException):
    """SQLSTATE 22034 - more than one sql json item."""

    pass


class NoSQLJsonItem(DataException):
    """SQLSTATE 22035 - no sql json item."""

    pass


class NonNumericSQLJsonItem(DataException):
    """SQLSTATE 22036 - non numeric sql json item."""

    pass


class NonUniqueKeysInAJsonObject(DataException):
    """SQLSTATE 22037 - non unique keys in a json object."""

    pass


class SingletonSQLJsonItemRequired(DataException):
    """SQLSTATE 22038 - singleton sql json item required."""

    pass


class SQLJsonArrayNotFound(DataException):
    """SQLSTATE 22039 - sql json array not found."""

    pass


class SQLJsonMemberNotFound(DataException):
    """SQLSTATE 2203A - sql json member not found."""

    pass


class SQLJsonNumberNotFound(DataException):
    """SQLSTATE 2203B - sql json number not found."""

    pass


class SQLJsonObjectNotFound(DataException):
    """SQLSTATE 2203C - sql json object not found."""

    pass


class TooManyJsonArrayElements(DataException):
    """SQLSTATE 2203D - too many json array elements."""

    pass


class TooManyJsonObjectMembers(DataException):
    """SQLSTATE 2203E - too many json object members."""

    pass


class SQLJsonScalarRequired(DataException):
    """SQLSTATE 2203F - sql json scalar required."""

    pass


class SQLJsonItemCannotBeCastToTargetType(DataException):
    """SQLSTATE 2203G - sql json item cannot be cast to target type."""

    pass


class IntegrityConstraintViolation(LibpqError):
    """SQLSTATE 23000 - integrity constraint violation."""

    pass


class RestrictViolation(IntegrityConstraintViolation):
    """SQLSTATE 23001 - restrict violation."""

    pass


class NotNullViolation(IntegrityConstraintViolation):
    """SQLSTATE 23502 - not null violation."""

    pass


class ForeignKeyViolation(IntegrityConstraintViolation):
    """SQLSTATE 23503 - foreign key violation."""

    pass


class UniqueViolation(IntegrityConstraintViolation):
    """SQLSTATE 23505 - unique violation."""

    pass


class CheckViolation(IntegrityConstraintViolation):
    """SQLSTATE 23514 - check violation."""

    pass


class ExclusionViolation(IntegrityConstraintViolation):
    """SQLSTATE 23P01 - exclusion violation."""

    pass


class InvalidCursorState(LibpqError):
    """SQLSTATE 24000 - invalid cursor state."""

    pass


class InvalidTransactionState(LibpqError):
    """SQLSTATE 25000 - invalid transaction state."""

    pass


class ActiveSQLTransaction(InvalidTransactionState):
    """SQLSTATE 25001 - active sql transaction."""

    pass


class BranchTransactionAlreadyActive(InvalidTransactionState):
    """SQLSTATE 25002 - branch transaction already active."""

    pass


class HeldCursorRequiresSameIsolationLevel(InvalidTransactionState):
    """SQLSTATE 25008 - held cursor requires same isolation level."""

    pass


class InappropriateAccessModeForBranchTransaction(InvalidTransactionState):
    """SQLSTATE 25003 - inappropriate access mode for branch transaction."""

    pass


class InappropriateIsolationLevelForBranchTransaction(InvalidTransactionState):
    """SQLSTATE 25004 - inappropriate isolation level for branch transaction."""

    pass


class NoActiveSQLTransactionForBranchTransaction(InvalidTransactionState):
    """SQLSTATE 25005 - no active sql transaction for branch transaction."""

    pass


class ReadOnlySQLTransaction(InvalidTransactionState):
    """SQLSTATE 25006 - read only sql transaction."""

    pass


class SchemaAndDataStatementMixingNotSupported(InvalidTransactionState):
    """SQLSTATE 25007 - schema and data statement mixing not supported."""

    pass


class NoActiveSQLTransaction(InvalidTransactionState):
    """SQLSTATE 25P01 - no active sql transaction."""

    pass


class InFailedSQLTransaction(InvalidTransactionState):
    """SQLSTATE 25P02 - in failed sql transaction."""

    pass


class IdleInTransactionSessionTimeout(InvalidTransactionState):
    """SQLSTATE 25P03 - idle in transaction session timeout."""

    pass


class TransactionTimeout(InvalidTransactionState):
    """SQLSTATE 25P04 - transaction timeout."""

    pass


class InvalidSQLStatementName(LibpqError):
    """SQLSTATE 26000 - invalid sql statement name."""

    pass


class TriggeredDataChangeViolation(LibpqError):
    """SQLSTATE 27000 - triggered data change violation."""

    pass


class InvalidAuthorizationSpecification(LibpqError):
    """SQLSTATE 28000 - invalid authorization specification."""

    pass


class InvalidPassword(InvalidAuthorizationSpecification):
    """SQLSTATE 28P01 - invalid password."""

    pass


class DependentPrivilegeDescriptorsStillExist(LibpqError):
    """SQLSTATE 2B000 - dependent privilege descriptors still exist."""

    pass


class DependentObjectsStillExist(DependentPrivilegeDescriptorsStillExist):
    """SQLSTATE 2BP01 - dependent objects still exist."""

    pass


class InvalidTransactionTermination(LibpqError):
    """SQLSTATE 2D000 - invalid transaction termination."""

    pass


class SQLRoutineException(LibpqError):
    """SQLSTATE 2F000 - sql routine exception."""

    pass


class FunctionExecutedNoReturnStatement(SQLRoutineException):
    """SQLSTATE 2F005 - function executed no return statement."""

    pass


class SREModifyingSQLDataNotPermitted(SQLRoutineException):
    """SQLSTATE 2F002 - modifying sql data not permitted."""

    pass


class SREProhibitedSQLStatementAttempted(SQLRoutineException):
    """SQLSTATE 2F003 - prohibited sql statement attempted."""

    pass


class SREReadingSQLDataNotPermitted(SQLRoutineException):
    """SQLSTATE 2F004 - reading sql data not permitted."""

    pass


class InvalidCursorName(LibpqError):
    """SQLSTATE 34000 - invalid cursor name."""

    pass


class ExternalRoutineException(LibpqError):
    """SQLSTATE 38000 - external routine exception."""

    pass


class ContainingSQLNotPermitted(ExternalRoutineException):
    """SQLSTATE 38001 - containing sql not permitted."""

    pass


class EREModifyingSQLDataNotPermitted(ExternalRoutineException):
    """SQLSTATE 38002 - modifying sql data not permitted."""

    pass


class EREProhibitedSQLStatementAttempted(ExternalRoutineException):
    """SQLSTATE 38003 - prohibited sql statement attempted."""

    pass


class EREReadingSQLDataNotPermitted(ExternalRoutineException):
    """SQLSTATE 38004 - reading sql data not permitted."""

    pass


class ExternalRoutineInvocationException(LibpqError):
    """SQLSTATE 39000 - external routine invocation exception."""

    pass


class InvalidSqlstateReturned(ExternalRoutineInvocationException):
    """SQLSTATE 39001 - invalid sqlstate returned."""

    pass


class ERIENullValueNotAllowed(ExternalRoutineInvocationException):
    """SQLSTATE 39004 - null value not allowed."""

    pass


class TriggerProtocolViolated(ExternalRoutineInvocationException):
    """SQLSTATE 39P01 - trigger protocol violated."""

    pass


class SrfProtocolViolated(ExternalRoutineInvocationException):
    """SQLSTATE 39P02 - srf protocol violated."""

    pass


class EventTriggerProtocolViolated(ExternalRoutineInvocationException):
    """SQLSTATE 39P03 - event trigger protocol violated."""

    pass


class SavepointException(LibpqError):
    """SQLSTATE 3B000 - savepoint exception."""

    pass


class InvalidSavepointSpecification(SavepointException):
    """SQLSTATE 3B001 - invalid savepoint specification."""

    pass


class InvalidCatalogName(LibpqError):
    """SQLSTATE 3D000 - invalid catalog name."""

    pass


class InvalidSchemaName(LibpqError):
    """SQLSTATE 3F000 - invalid schema name."""

    pass


class TransactionRollback(LibpqError):
    """SQLSTATE 40000 - transaction rollback."""

    pass


class TransactionIntegrityConstraintViolation(TransactionRollback):
    """SQLSTATE 40002 - transaction integrity constraint violation."""

    pass


class SerializationFailure(TransactionRollback):
    """SQLSTATE 40001 - serialization failure."""

    pass


class StatementCompletionUnknown(TransactionRollback):
    """SQLSTATE 40003 - statement completion unknown."""

    pass


class DeadlockDetected(TransactionRollback):
    """SQLSTATE 40P01 - deadlock detected."""

    pass


class SyntaxErrorOrAccessRuleViolation(LibpqError):
    """SQLSTATE 42000 - syntax error or access rule violation."""

    pass


class SyntaxError(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42601 - syntax error."""

    pass


class InsufficientPrivilege(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42501 - insufficient privilege."""

    pass


class CannotCoerce(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42846 - cannot coerce."""

    pass


class GroupingError(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42803 - grouping error."""

    pass


class WindowingError(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P20 - windowing error."""

    pass


class InvalidRecursion(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P19 - invalid recursion."""

    pass


class InvalidForeignKey(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42830 - invalid foreign key."""

    pass


class InvalidName(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42602 - invalid name."""

    pass


class NameTooLong(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42622 - name too long."""

    pass


class ReservedName(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42939 - reserved name."""

    pass


class DatatypeMismatch(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42804 - datatype mismatch."""

    pass


class IndeterminateDatatype(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P18 - indeterminate datatype."""

    pass


class CollationMismatch(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P21 - collation mismatch."""

    pass


class IndeterminateCollation(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P22 - indeterminate collation."""

    pass


class WrongObjectType(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42809 - wrong object type."""

    pass


class GeneratedAlways(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 428C9 - generated always."""

    pass


class UndefinedColumn(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42703 - undefined column."""

    pass


class UndefinedFunction(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42883 - undefined function."""

    pass


class UndefinedTable(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P01 - undefined table."""

    pass


class UndefinedParameter(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P02 - undefined parameter."""

    pass


class UndefinedObject(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42704 - undefined object."""

    pass


class DuplicateColumn(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42701 - duplicate column."""

    pass


class DuplicateCursor(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P03 - duplicate cursor."""

    pass


class DuplicateDatabase(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P04 - duplicate database."""

    pass


class DuplicateFunction(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42723 - duplicate function."""

    pass


class DuplicatePreparedStatement(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P05 - duplicate prepared statement."""

    pass


class DuplicateSchema(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P06 - duplicate schema."""

    pass


class DuplicateTable(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P07 - duplicate table."""

    pass


class DuplicateAlias(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42712 - duplicate alias."""

    pass


class DuplicateObject(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42710 - duplicate object."""

    pass


class AmbiguousColumn(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42702 - ambiguous column."""

    pass


class AmbiguousFunction(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42725 - ambiguous function."""

    pass


class AmbiguousParameter(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P08 - ambiguous parameter."""

    pass


class AmbiguousAlias(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P09 - ambiguous alias."""

    pass


class InvalidColumnReference(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P10 - invalid column reference."""

    pass


class InvalidColumnDefinition(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42611 - invalid column definition."""

    pass


class InvalidCursorDefinition(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P11 - invalid cursor definition."""

    pass


class InvalidDatabaseDefinition(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P12 - invalid database definition."""

    pass


class InvalidFunctionDefinition(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P13 - invalid function definition."""

    pass


class InvalidPreparedStatementDefinition(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P14 - invalid prepared statement definition."""

    pass


class InvalidSchemaDefinition(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P15 - invalid schema definition."""

    pass


class InvalidTableDefinition(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P16 - invalid table definition."""

    pass


class InvalidObjectDefinition(SyntaxErrorOrAccessRuleViolation):
    """SQLSTATE 42P17 - invalid object definition."""

    pass


class WithCheckOptionViolation(LibpqError):
    """SQLSTATE 44000 - with check option violation."""

    pass


class InsufficientResources(LibpqError):
    """SQLSTATE 53000 - insufficient resources."""

    pass


class DiskFull(InsufficientResources):
    """SQLSTATE 53100 - disk full."""

    pass


class OutOfMemory(InsufficientResources):
    """SQLSTATE 53200 - out of memory."""

    pass


class TooManyConnections(InsufficientResources):
    """SQLSTATE 53300 - too many connections."""

    pass


class ConfigurationLimitExceeded(InsufficientResources):
    """SQLSTATE 53400 - configuration limit exceeded."""

    pass


class ProgramLimitExceeded(LibpqError):
    """SQLSTATE 54000 - program limit exceeded."""

    pass


class StatementTooComplex(ProgramLimitExceeded):
    """SQLSTATE 54001 - statement too complex."""

    pass


class TooManyColumns(ProgramLimitExceeded):
    """SQLSTATE 54011 - too many columns."""

    pass


class TooManyArguments(ProgramLimitExceeded):
    """SQLSTATE 54023 - too many arguments."""

    pass


class ObjectNotInPrerequisiteState(LibpqError):
    """SQLSTATE 55000 - object not in prerequisite state."""

    pass


class ObjectInUse(ObjectNotInPrerequisiteState):
    """SQLSTATE 55006 - object in use."""

    pass


class CantChangeRuntimeParam(ObjectNotInPrerequisiteState):
    """SQLSTATE 55P02 - cant change runtime param."""

    pass


class LockNotAvailable(ObjectNotInPrerequisiteState):
    """SQLSTATE 55P03 - lock not available."""

    pass


class UnsafeNewEnumValueUsage(ObjectNotInPrerequisiteState):
    """SQLSTATE 55P04 - unsafe new enum value usage."""

    pass


class OperatorIntervention(LibpqError):
    """SQLSTATE 57000 - operator intervention."""

    pass


class QueryCanceled(OperatorIntervention):
    """SQLSTATE 57014 - query canceled."""

    pass


class AdminShutdown(OperatorIntervention):
    """SQLSTATE 57P01 - admin shutdown."""

    pass


class CrashShutdown(OperatorIntervention):
    """SQLSTATE 57P02 - crash shutdown."""

    pass


class CannotConnectNow(OperatorIntervention):
    """SQLSTATE 57P03 - cannot connect now."""

    pass


class DatabaseDropped(OperatorIntervention):
    """SQLSTATE 57P04 - database dropped."""

    pass


class IdleSessionTimeout(OperatorIntervention):
    """SQLSTATE 57P05 - idle session timeout."""

    pass


class SystemError(LibpqError):
    """SQLSTATE 58000 - system error."""

    pass


class IoError(SystemError):
    """SQLSTATE 58030 - io error."""

    pass


class UndefinedFile(SystemError):
    """SQLSTATE 58P01 - undefined file."""

    pass


class DuplicateFile(SystemError):
    """SQLSTATE 58P02 - duplicate file."""

    pass


class FileNameTooLong(SystemError):
    """SQLSTATE 58P03 - file name too long."""

    pass


class ConfigFileError(LibpqError):
    """SQLSTATE F0000 - config file error."""

    pass


class LockFileExists(ConfigFileError):
    """SQLSTATE F0001 - lock file exists."""

    pass


class FDWError(LibpqError):
    """SQLSTATE HV000 - fdw error."""

    pass


class FDWColumnNameNotFound(FDWError):
    """SQLSTATE HV005 - fdw column name not found."""

    pass


class FDWDynamicParameterValueNeeded(FDWError):
    """SQLSTATE HV002 - fdw dynamic parameter value needed."""

    pass


class FDWFunctionSequenceError(FDWError):
    """SQLSTATE HV010 - fdw function sequence error."""

    pass


class FDWInconsistentDescriptorInformation(FDWError):
    """SQLSTATE HV021 - fdw inconsistent descriptor information."""

    pass


class FDWInvalidAttributeValue(FDWError):
    """SQLSTATE HV024 - fdw invalid attribute value."""

    pass


class FDWInvalidColumnName(FDWError):
    """SQLSTATE HV007 - fdw invalid column name."""

    pass


class FDWInvalidColumnNumber(FDWError):
    """SQLSTATE HV008 - fdw invalid column number."""

    pass


class FDWInvalidDataType(FDWError):
    """SQLSTATE HV004 - fdw invalid data type."""

    pass


class FDWInvalidDataTypeDescriptors(FDWError):
    """SQLSTATE HV006 - fdw invalid data type descriptors."""

    pass


class FDWInvalidDescriptorFieldIdentifier(FDWError):
    """SQLSTATE HV091 - fdw invalid descriptor field identifier."""

    pass


class FDWInvalidHandle(FDWError):
    """SQLSTATE HV00B - fdw invalid handle."""

    pass


class FDWInvalidOptionIndex(FDWError):
    """SQLSTATE HV00C - fdw invalid option index."""

    pass


class FDWInvalidOptionName(FDWError):
    """SQLSTATE HV00D - fdw invalid option name."""

    pass


class FDWInvalidStringLengthOrBufferLength(FDWError):
    """SQLSTATE HV090 - fdw invalid string length or buffer length."""

    pass


class FDWInvalidStringFormat(FDWError):
    """SQLSTATE HV00A - fdw invalid string format."""

    pass


class FDWInvalidUseOfNullPointer(FDWError):
    """SQLSTATE HV009 - fdw invalid use of null pointer."""

    pass


class FDWTooManyHandles(FDWError):
    """SQLSTATE HV014 - fdw too many handles."""

    pass


class FDWOutOfMemory(FDWError):
    """SQLSTATE HV001 - fdw out of memory."""

    pass


class FDWNoSchemas(FDWError):
    """SQLSTATE HV00P - fdw no schemas."""

    pass


class FDWOptionNameNotFound(FDWError):
    """SQLSTATE HV00J - fdw option name not found."""

    pass


class FDWReplyHandle(FDWError):
    """SQLSTATE HV00K - fdw reply handle."""

    pass


class FDWSchemaNotFound(FDWError):
    """SQLSTATE HV00Q - fdw schema not found."""

    pass


class FDWTableNotFound(FDWError):
    """SQLSTATE HV00R - fdw table not found."""

    pass


class FDWUnableToCreateExecution(FDWError):
    """SQLSTATE HV00L - fdw unable to create execution."""

    pass


class FDWUnableToCreateReply(FDWError):
    """SQLSTATE HV00M - fdw unable to create reply."""

    pass


class FDWUnableToEstablishConnection(FDWError):
    """SQLSTATE HV00N - fdw unable to establish connection."""

    pass


class PlpgsqlError(LibpqError):
    """SQLSTATE P0000 - plpgsql error."""

    pass


class RaiseException(PlpgsqlError):
    """SQLSTATE P0001 - raise exception."""

    pass


class NoDataFound(PlpgsqlError):
    """SQLSTATE P0002 - no data found."""

    pass


class TooManyRows(PlpgsqlError):
    """SQLSTATE P0003 - too many rows."""

    pass


class AssertFailure(PlpgsqlError):
    """SQLSTATE P0004 - assert failure."""

    pass


class InternalError(LibpqError):
    """SQLSTATE XX000 - internal error."""

    pass


class DataCorrupted(InternalError):
    """SQLSTATE XX001 - data corrupted."""

    pass


class IndexCorrupted(InternalError):
    """SQLSTATE XX002 - index corrupted."""

    pass


SQLSTATE_TO_EXCEPTION: Dict[str, type] = {
    "00000": SuccessfulCompletion,
    "01000": Warning,
    "0100C": DynamicResultSetsReturnedWarning,
    "01008": ImplicitZeroBitPaddingWarning,
    "01003": NullValueEliminatedInSetFunctionWarning,
    "01007": PrivilegeNotGrantedWarning,
    "01006": PrivilegeNotRevokedWarning,
    "01004": StringDataRightTruncationWarning,
    "01P01": DeprecatedFeatureWarning,
    "02000": NoData,
    "02001": NoAdditionalDynamicResultSetsReturned,
    "03000": SQLStatementNotYetComplete,
    "08000": ConnectionException,
    "08003": ConnectionDoesNotExist,
    "08006": ConnectionFailure,
    "08001": SQLClientUnableToEstablishSQLConnection,
    "08004": SQLServerRejectedEstablishmentOfSQLConnection,
    "08007": TransactionResolutionUnknown,
    "08P01": ProtocolViolation,
    "09000": TriggeredActionException,
    "0A000": FeatureNotSupported,
    "0B000": InvalidTransactionInitiation,
    "0F000": LocatorException,
    "0F001": InvalidLocatorSpecification,
    "0L000": InvalidGrantor,
    "0LP01": InvalidGrantOperation,
    "0P000": InvalidRoleSpecification,
    "0Z000": DiagnosticsException,
    "0Z002": StackedDiagnosticsAccessedWithoutActiveHandler,
    "10608": InvalidArgumentForXquery,
    "20000": CaseNotFound,
    "21000": CardinalityViolation,
    "22000": DataException,
    "2202E": ArraySubscriptError,
    "22021": CharacterNotInRepertoire,
    "22008": DatetimeFieldOverflow,
    "22012": DivisionByZero,
    "22005": ErrorInAssignment,
    "2200B": EscapeCharacterConflict,
    "22022": IndicatorOverflow,
    "22015": IntervalFieldOverflow,
    "2201E": InvalidArgumentForLogarithm,
    "22014": InvalidArgumentForNtileFunction,
    "22016": InvalidArgumentForNthValueFunction,
    "2201F": InvalidArgumentForPowerFunction,
    "2201G": InvalidArgumentForWidthBucketFunction,
    "22018": InvalidCharacterValueForCast,
    "22007": InvalidDatetimeFormat,
    "22019": InvalidEscapeCharacter,
    "2200D": InvalidEscapeOctet,
    "22025": InvalidEscapeSequence,
    "22P06": NonstandardUseOfEscapeCharacter,
    "22010": InvalidIndicatorParameterValue,
    "22023": InvalidParameterValue,
    "22013": InvalidPrecedingOrFollowingSize,
    "2201B": InvalidRegularExpression,
    "2201W": InvalidRowCountInLimitClause,
    "2201X": InvalidRowCountInResultOffsetClause,
    "2202H": InvalidTablesampleArgument,
    "2202G": InvalidTablesampleRepeat,
    "22009": InvalidTimeZoneDisplacementValue,
    "2200C": InvalidUseOfEscapeCharacter,
    "2200G": MostSpecificTypeMismatch,
    "22004": NullValueNotAllowed,
    "22002": NullValueNoIndicatorParameter,
    "22003": NumericValueOutOfRange,
    "2200H": SequenceGeneratorLimitExceeded,
    "22026": StringDataLengthMismatch,
    "22001": StringDataRightTruncation,
    "22011": SubstringError,
    "22027": TrimError,
    "22024": UnterminatedCString,
    "2200F": ZeroLengthCharacterString,
    "22P01": FloatingPointException,
    "22P02": InvalidTextRepresentation,
    "22P03": InvalidBinaryRepresentation,
    "22P04": BadCopyFileFormat,
    "22P05": UntranslatableCharacter,
    "2200L": NotAnXmlDocument,
    "2200M": InvalidXmlDocument,
    "2200N": InvalidXmlContent,
    "2200S": InvalidXmlComment,
    "2200T": InvalidXmlProcessingInstruction,
    "22030": DuplicateJsonObjectKeyValue,
    "22031": InvalidArgumentForSQLJsonDatetimeFunction,
    "22032": InvalidJsonText,
    "22033": InvalidSQLJsonSubscript,
    "22034": MoreThanOneSQLJsonItem,
    "22035": NoSQLJsonItem,
    "22036": NonNumericSQLJsonItem,
    "22037": NonUniqueKeysInAJsonObject,
    "22038": SingletonSQLJsonItemRequired,
    "22039": SQLJsonArrayNotFound,
    "2203A": SQLJsonMemberNotFound,
    "2203B": SQLJsonNumberNotFound,
    "2203C": SQLJsonObjectNotFound,
    "2203D": TooManyJsonArrayElements,
    "2203E": TooManyJsonObjectMembers,
    "2203F": SQLJsonScalarRequired,
    "2203G": SQLJsonItemCannotBeCastToTargetType,
    "23000": IntegrityConstraintViolation,
    "23001": RestrictViolation,
    "23502": NotNullViolation,
    "23503": ForeignKeyViolation,
    "23505": UniqueViolation,
    "23514": CheckViolation,
    "23P01": ExclusionViolation,
    "24000": InvalidCursorState,
    "25000": InvalidTransactionState,
    "25001": ActiveSQLTransaction,
    "25002": BranchTransactionAlreadyActive,
    "25008": HeldCursorRequiresSameIsolationLevel,
    "25003": InappropriateAccessModeForBranchTransaction,
    "25004": InappropriateIsolationLevelForBranchTransaction,
    "25005": NoActiveSQLTransactionForBranchTransaction,
    "25006": ReadOnlySQLTransaction,
    "25007": SchemaAndDataStatementMixingNotSupported,
    "25P01": NoActiveSQLTransaction,
    "25P02": InFailedSQLTransaction,
    "25P03": IdleInTransactionSessionTimeout,
    "25P04": TransactionTimeout,
    "26000": InvalidSQLStatementName,
    "27000": TriggeredDataChangeViolation,
    "28000": InvalidAuthorizationSpecification,
    "28P01": InvalidPassword,
    "2B000": DependentPrivilegeDescriptorsStillExist,
    "2BP01": DependentObjectsStillExist,
    "2D000": InvalidTransactionTermination,
    "2F000": SQLRoutineException,
    "2F005": FunctionExecutedNoReturnStatement,
    "2F002": SREModifyingSQLDataNotPermitted,
    "2F003": SREProhibitedSQLStatementAttempted,
    "2F004": SREReadingSQLDataNotPermitted,
    "34000": InvalidCursorName,
    "38000": ExternalRoutineException,
    "38001": ContainingSQLNotPermitted,
    "38002": EREModifyingSQLDataNotPermitted,
    "38003": EREProhibitedSQLStatementAttempted,
    "38004": EREReadingSQLDataNotPermitted,
    "39000": ExternalRoutineInvocationException,
    "39001": InvalidSqlstateReturned,
    "39004": ERIENullValueNotAllowed,
    "39P01": TriggerProtocolViolated,
    "39P02": SrfProtocolViolated,
    "39P03": EventTriggerProtocolViolated,
    "3B000": SavepointException,
    "3B001": InvalidSavepointSpecification,
    "3D000": InvalidCatalogName,
    "3F000": InvalidSchemaName,
    "40000": TransactionRollback,
    "40002": TransactionIntegrityConstraintViolation,
    "40001": SerializationFailure,
    "40003": StatementCompletionUnknown,
    "40P01": DeadlockDetected,
    "42000": SyntaxErrorOrAccessRuleViolation,
    "42601": SyntaxError,
    "42501": InsufficientPrivilege,
    "42846": CannotCoerce,
    "42803": GroupingError,
    "42P20": WindowingError,
    "42P19": InvalidRecursion,
    "42830": InvalidForeignKey,
    "42602": InvalidName,
    "42622": NameTooLong,
    "42939": ReservedName,
    "42804": DatatypeMismatch,
    "42P18": IndeterminateDatatype,
    "42P21": CollationMismatch,
    "42P22": IndeterminateCollation,
    "42809": WrongObjectType,
    "428C9": GeneratedAlways,
    "42703": UndefinedColumn,
    "42883": UndefinedFunction,
    "42P01": UndefinedTable,
    "42P02": UndefinedParameter,
    "42704": UndefinedObject,
    "42701": DuplicateColumn,
    "42P03": DuplicateCursor,
    "42P04": DuplicateDatabase,
    "42723": DuplicateFunction,
    "42P05": DuplicatePreparedStatement,
    "42P06": DuplicateSchema,
    "42P07": DuplicateTable,
    "42712": DuplicateAlias,
    "42710": DuplicateObject,
    "42702": AmbiguousColumn,
    "42725": AmbiguousFunction,
    "42P08": AmbiguousParameter,
    "42P09": AmbiguousAlias,
    "42P10": InvalidColumnReference,
    "42611": InvalidColumnDefinition,
    "42P11": InvalidCursorDefinition,
    "42P12": InvalidDatabaseDefinition,
    "42P13": InvalidFunctionDefinition,
    "42P14": InvalidPreparedStatementDefinition,
    "42P15": InvalidSchemaDefinition,
    "42P16": InvalidTableDefinition,
    "42P17": InvalidObjectDefinition,
    "44000": WithCheckOptionViolation,
    "53000": InsufficientResources,
    "53100": DiskFull,
    "53200": OutOfMemory,
    "53300": TooManyConnections,
    "53400": ConfigurationLimitExceeded,
    "54000": ProgramLimitExceeded,
    "54001": StatementTooComplex,
    "54011": TooManyColumns,
    "54023": TooManyArguments,
    "55000": ObjectNotInPrerequisiteState,
    "55006": ObjectInUse,
    "55P02": CantChangeRuntimeParam,
    "55P03": LockNotAvailable,
    "55P04": UnsafeNewEnumValueUsage,
    "57000": OperatorIntervention,
    "57014": QueryCanceled,
    "57P01": AdminShutdown,
    "57P02": CrashShutdown,
    "57P03": CannotConnectNow,
    "57P04": DatabaseDropped,
    "57P05": IdleSessionTimeout,
    "58000": SystemError,
    "58030": IoError,
    "58P01": UndefinedFile,
    "58P02": DuplicateFile,
    "58P03": FileNameTooLong,
    "F0000": ConfigFileError,
    "F0001": LockFileExists,
    "HV000": FDWError,
    "HV005": FDWColumnNameNotFound,
    "HV002": FDWDynamicParameterValueNeeded,
    "HV010": FDWFunctionSequenceError,
    "HV021": FDWInconsistentDescriptorInformation,
    "HV024": FDWInvalidAttributeValue,
    "HV007": FDWInvalidColumnName,
    "HV008": FDWInvalidColumnNumber,
    "HV004": FDWInvalidDataType,
    "HV006": FDWInvalidDataTypeDescriptors,
    "HV091": FDWInvalidDescriptorFieldIdentifier,
    "HV00B": FDWInvalidHandle,
    "HV00C": FDWInvalidOptionIndex,
    "HV00D": FDWInvalidOptionName,
    "HV090": FDWInvalidStringLengthOrBufferLength,
    "HV00A": FDWInvalidStringFormat,
    "HV009": FDWInvalidUseOfNullPointer,
    "HV014": FDWTooManyHandles,
    "HV001": FDWOutOfMemory,
    "HV00P": FDWNoSchemas,
    "HV00J": FDWOptionNameNotFound,
    "HV00K": FDWReplyHandle,
    "HV00Q": FDWSchemaNotFound,
    "HV00R": FDWTableNotFound,
    "HV00L": FDWUnableToCreateExecution,
    "HV00M": FDWUnableToCreateReply,
    "HV00N": FDWUnableToEstablishConnection,
    "P0000": PlpgsqlError,
    "P0001": RaiseException,
    "P0002": NoDataFound,
    "P0003": TooManyRows,
    "P0004": AssertFailure,
    "XX000": InternalError,
    "XX001": DataCorrupted,
    "XX002": IndexCorrupted,
}


__all__ = [
    "InvalidCursorName",
    "UndefinedParameter",
    "UndefinedColumn",
    "NotAnXmlDocument",
    "FDWOutOfMemory",
    "InvalidRoleSpecification",
    "InvalidArgumentForNthValueFunction",
    "SQLJsonObjectNotFound",
    "FDWSchemaNotFound",
    "InvalidParameterValue",
    "InvalidTableDefinition",
    "AssertFailure",
    "FDWInvalidOptionName",
    "InvalidEscapeOctet",
    "ReadOnlySQLTransaction",
    "ExternalRoutineInvocationException",
    "CrashShutdown",
    "FDWInvalidOptionIndex",
    "NotNullViolation",
    "ConfigFileError",
    "InvalidSQLJsonSubscript",
    "InvalidForeignKey",
    "InsufficientResources",
    "ObjectNotInPrerequisiteState",
    "InvalidRowCountInLimitClause",
    "IntervalFieldOverflow",
    "CollationMismatch",
    "InvalidArgumentForNtileFunction",
    "InvalidCharacterValueForCast",
    "NonUniqueKeysInAJsonObject",
    "DependentPrivilegeDescriptorsStillExist",
    "InFailedSQLTransaction",
    "GroupingError",
    "TransactionTimeout",
    "CaseNotFound",
    "ConnectionException",
    "DuplicateJsonObjectKeyValue",
    "InvalidSchemaDefinition",
    "FDWUnableToCreateReply",
    "UndefinedTable",
    "SequenceGeneratorLimitExceeded",
    "InvalidJsonText",
    "IdleSessionTimeout",
    "NullValueNotAllowed",
    "BranchTransactionAlreadyActive",
    "InvalidGrantOperation",
    "NullValueNoIndicatorParameter",
    "ProtocolViolation",
    "FDWInvalidDataTypeDescriptors",
    "TriggeredDataChangeViolation",
    "ExternalRoutineException",
    "InvalidSqlstateReturned",
    "PlpgsqlError",
    "InvalidXmlContent",
    "TriggeredActionException",
    "SQLClientUnableToEstablishSQLConnection",
    "FDWTableNotFound",
    "NumericValueOutOfRange",
    "RestrictViolation",
    "AmbiguousParameter",
    "StatementTooComplex",
    "UnsafeNewEnumValueUsage",
    "NonNumericSQLJsonItem",
    "InvalidIndicatorParameterValue",
    "ExclusionViolation",
    "OperatorIntervention",
    "QueryCanceled",
    "Warning",
    "InvalidArgumentForSQLJsonDatetimeFunction",
    "ForeignKeyViolation",
    "StringDataLengthMismatch",
    "SQLRoutineException",
    "TooManyConnections",
    "TooManyJsonObjectMembers",
    "NoData",
    "UntranslatableCharacter",
    "FDWUnableToEstablishConnection",
    "LockFileExists",
    "SREReadingSQLDataNotPermitted",
    "IndeterminateDatatype",
    "CheckViolation",
    "InvalidDatabaseDefinition",
    "NoActiveSQLTransactionForBranchTransaction",
    "SQLServerRejectedEstablishmentOfSQLConnection",
    "DuplicateFile",
    "FDWInvalidColumnNumber",
    "TransactionRollback",
    "MoreThanOneSQLJsonItem",
    "WithCheckOptionViolation",
    "FDWNoSchemas",
    "GeneratedAlways",
    "CannotConnectNow",
    "CardinalityViolation",
    "InvalidAuthorizationSpecification",
    "SQLJsonNumberNotFound",
    "SQLJsonMemberNotFound",
    "InvalidUseOfEscapeCharacter",
    "UnterminatedCString",
    "TrimError",
    "SrfProtocolViolated",
    "DiskFull",
    "TooManyColumns",
    "InvalidObjectDefinition",
    "InvalidArgumentForLogarithm",
    "TooManyJsonArrayElements",
    "OutOfMemory",
    "EREProhibitedSQLStatementAttempted",
    "FDWInvalidStringFormat",
    "StackedDiagnosticsAccessedWithoutActiveHandler",
    "SchemaAndDataStatementMixingNotSupported",
    "InternalError",
    "InvalidEscapeCharacter",
    "FDWError",
    "ImplicitZeroBitPaddingWarning",
    "DivisionByZero",
    "InvalidTablesampleArgument",
    "DeadlockDetected",
    "CantChangeRuntimeParam",
    "UndefinedObject",
    "UniqueViolation",
    "InvalidCursorDefinition",
    "ConnectionFailure",
    "UndefinedFunction",
    "FDWFunctionSequenceError",
    "ErrorInAssignment",
    "SuccessfulCompletion",
    "StringDataRightTruncation",
    "FDWTooManyHandles",
    "FDWInvalidDataType",
    "ActiveSQLTransaction",
    "InvalidTextRepresentation",
    "InvalidSQLStatementName",
    "PrivilegeNotGrantedWarning",
    "SREModifyingSQLDataNotPermitted",
    "IndeterminateCollation",
    "SystemError",
    "NullValueEliminatedInSetFunctionWarning",
    "DependentObjectsStillExist",
    "InvalidSchemaName",
    "DuplicateColumn",
    "FunctionExecutedNoReturnStatement",
    "InvalidColumnDefinition",
    "DynamicResultSetsReturnedWarning",
    "IdleInTransactionSessionTimeout",
    "StatementCompletionUnknown",
    "CannotCoerce",
    "InvalidTransactionState",
    "DuplicateTable",
    "BadCopyFileFormat",
    "ZeroLengthCharacterString",
    "SyntaxErrorOrAccessRuleViolation",
    "SingletonSQLJsonItemRequired",
    "IndexCorrupted",
    "FDWInvalidColumnName",
    "DataCorrupted",
    "ERIENullValueNotAllowed",
    "ArraySubscriptError",
    "FDWReplyHandle",
    "DiagnosticsException",
    "InvalidTablesampleRepeat",
    "SQLJsonItemCannotBeCastToTargetType",
    "FDWInvalidHandle",
    "InvalidPassword",
    "InvalidEscapeSequence",
    "EscapeCharacterConflict",
    "InvalidSavepointSpecification",
    "FDWInvalidAttributeValue",
    "ContainingSQLNotPermitted",
    "LocatorException",
    "DatatypeMismatch",
    "InvalidCursorState",
    "InvalidName",
    "IndicatorOverflow",
    "ReservedName",
    "DatetimeFieldOverflow",
    "FDWInconsistentDescriptorInformation",
    "FloatingPointException",
    "AmbiguousAlias",
    "InvalidRecursion",
    "WrongObjectType",
    "UndefinedFile",
    "LockNotAvailable",
    "InvalidRowCountInResultOffsetClause",
    "ObjectInUse",
    "DeprecatedFeatureWarning",
    "FDWDynamicParameterValueNeeded",
    "DuplicateFunction",
    "InvalidXmlDocument",
    "StringDataRightTruncationWarning",
    "DuplicatePreparedStatement",
    "InvalidGrantor",
    "EventTriggerProtocolViolated",
    "FDWInvalidUseOfNullPointer",
    "FDWUnableToCreateExecution",
    "ConnectionDoesNotExist",
    "InvalidCatalogName",
    "InvalidArgumentForXquery",
    "FDWColumnNameNotFound",
    "TransactionIntegrityConstraintViolation",
    "InvalidPreparedStatementDefinition",
    "FDWInvalidDescriptorFieldIdentifier",
    "FDWOptionNameNotFound",
    "InvalidArgumentForPowerFunction",
    "FDWInvalidStringLengthOrBufferLength",
    "SREProhibitedSQLStatementAttempted",
    "NoDataFound",
    "DuplicateDatabase",
    "FeatureNotSupported",
    "IntegrityConstraintViolation",
    "AmbiguousColumn",
    "PrivilegeNotRevokedWarning",
    "FileNameTooLong",
    "InvalidArgumentForWidthBucketFunction",
    "HeldCursorRequiresSameIsolationLevel",
    "NoSQLJsonItem",
    "IoError",
    "SavepointException",
    "NoActiveSQLTransaction",
    "InvalidFunctionDefinition",
    "AdminShutdown",
    "DatabaseDropped",
    "InvalidRegularExpression",
    "WindowingError",
    "InvalidColumnReference",
    "InvalidBinaryRepresentation",
    "SQLJsonScalarRequired",
    "ConfigurationLimitExceeded",
    "SyntaxError",
    "SerializationFailure",
    "ProgramLimitExceeded",
    "DuplicateSchema",
    "SQLStatementNotYetComplete",
    "LibpqError",
    "DataException",
    "SubstringError",
    "InvalidLocatorSpecification",
    "InappropriateAccessModeForBranchTransaction",
    "EREModifyingSQLDataNotPermitted",
    "InsufficientPrivilege",
    "NoAdditionalDynamicResultSetsReturned",
    "SQLJsonArrayNotFound",
    "NameTooLong",
    "InvalidTimeZoneDisplacementValue",
    "InappropriateIsolationLevelForBranchTransaction",
    "RaiseException",
    "EREReadingSQLDataNotPermitted",
    "TriggerProtocolViolated",
    "NonstandardUseOfEscapeCharacter",
    "InvalidTransactionInitiation",
    "DuplicateAlias",
    "TransactionResolutionUnknown",
    "TooManyRows",
    "InvalidXmlComment",
    "MostSpecificTypeMismatch",
    "DuplicateObject",
    "DuplicateCursor",
    "AmbiguousFunction",
    "TooManyArguments",
    "InvalidXmlProcessingInstruction",
    "InvalidTransactionTermination",
    "InvalidDatetimeFormat",
    "InvalidPrecedingOrFollowingSize",
    "CharacterNotInRepertoire",
    "SQLSTATE_TO_EXCEPTION",
]
