#!/usr/bin/env python3
# Copyright (c) 2025, PostgreSQL Global Development Group

"""
Generate src/test/pytest/libpq/_generated_errors.py from errcodes.txt.
"""

import sys
from pathlib import Path


ACRONYMS = {"sql", "fdw"}
WORD_MAP = {
    "sqlclient": "SQLClient",
    "sqlserver": "SQLServer",
    "sqlconnection": "SQLConnection",
}


def snake_to_pascal(name: str) -> str:
    """Convert snake_case to PascalCase, keeping acronyms uppercase."""
    words = []
    for word in name.split("_"):
        if word in WORD_MAP:
            words.append(WORD_MAP[word])
        elif word in ACRONYMS:
            words.append(word.upper())
        else:
            words.append(word.capitalize())
    return "".join(words)


def parse_errcodes(path: Path):
    """Parse errcodes.txt and return list of (sqlstate, macro_name, spec_name) tuples."""
    errors = []

    with open(path) as f:
        for line in f:
            parts = line.split()
            if len(parts) >= 4 and len(parts[0]) == 5:
                sqlstate, _, macro_name, spec_name = parts[:4]
                errors.append((sqlstate, macro_name, spec_name))

    return errors


def macro_to_class_name(macro_name: str) -> str:
    """Convert ERRCODE_FOO_BAR to FooBar."""
    name = macro_name.removeprefix("ERRCODE_")
    # Move WARNING prefix to the end as a suffix
    if name.startswith("WARNING_"):
        name = name.removeprefix("WARNING_") + "_WARNING"
    return snake_to_pascal(name.lower())


def generate_errors(errcodes_path: Path):
    """Generate the _generated_errors.py content."""
    errors = parse_errcodes(errcodes_path)

    # Find spec_names that appear more than once (collisions)
    spec_name_counts: dict[str, int] = {}
    for _, _, spec_name in errors:
        spec_name_counts[spec_name] = spec_name_counts.get(spec_name, 0) + 1
    colliding_spec_names = {
        name for name, count in spec_name_counts.items() if count > 1
    }

    lines = [
        "# Copyright (c) 2025, PostgreSQL Global Development Group",
        "# This file is generated by src/tools/generate_pytest_libpq_errors.py - do not edit directly.",
        "",
        '"""',
        "Generated PostgreSQL error classes mapped from SQLSTATE codes.",
        '"""',
        "",
        "from typing import Dict",
        "",
        "from ._error_base import LibpqError, LibpqWarning",
        "",
        "",
    ]

    generated_classes = {"LibpqError"}
    sqlstate_to_exception = {}

    for sqlstate, macro_name, spec_name in errors:
        # 000 errors define the parent class for all errors in this SQLSTATE class
        if sqlstate.endswith("000"):
            exc_name = snake_to_pascal(spec_name)
            if exc_name == "Warning":
                parent = "LibpqWarning"
            else:
                parent = "LibpqError"
        else:
            if spec_name in colliding_spec_names:
                exc_name = macro_to_class_name(macro_name)
            else:
                exc_name = snake_to_pascal(spec_name)
            # Use parent class if available, otherwise LibpqError
            parent = sqlstate_to_exception.get(sqlstate[:2] + "000", "LibpqError")
            # Warnings should end with "Warning"
            if parent == "Warning" and not exc_name.endswith("Warning"):
                exc_name += "Warning"

        generated_classes.add(exc_name)
        sqlstate_to_exception[sqlstate] = exc_name
        lines.extend(
            [
                f"class {exc_name}({parent}):",
                f'    """SQLSTATE {sqlstate} - {spec_name.replace("_", " ")}."""',
                "",
                "    pass",
                "",
                "",
            ]
        )

    lines.append("SQLSTATE_TO_EXCEPTION: Dict[str, type] = {")
    for sqlstate, exc_name in sqlstate_to_exception.items():
        lines.append(f'    "{sqlstate}": {exc_name},')
    lines.extend(["}", "", ""])

    all_exports = list(generated_classes) + ["SQLSTATE_TO_EXCEPTION"]
    lines.append("__all__ = [")
    for name in all_exports:
        lines.append(f'    "{name}",')
    lines.append("]")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    script_dir = Path(__file__).resolve().parent
    src_root = script_dir.parent.parent

    errcodes_path = src_root / "src" / "backend" / "utils" / "errcodes.txt"
    output_path = (
        src_root / "src" / "test" / "pytest" / "libpq" / "_generated_errors.py"
    )

    if not errcodes_path.exists():
        print(f"Error: {errcodes_path} not found", file=sys.stderr)
        sys.exit(1)

    output = generate_errors(errcodes_path)
    output_path.write_text(output)
    print(f"Generated {output_path}")
